serenity.project.name=FoodTech Register Automation
webdriver.driver=chrome
webdriver.base.url=http://localhost:5173
headless.mode=false
serenity.browser.maximized=true
webdriver.chrome.arguments=--start-maximized
chrome.switches=--start-maximized
serenity.take.screenshots=FOR_EACH_ACTION
serenity.logging=VERBOSE
serenity.verbose.steps=true
serenity.console.colors=true
serenity.report.encoding=UTF-8
